<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>HighPredsMod</AssemblyName>
    <Product>HighPredsMod</Product>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp.dll" />
    <Reference Include="BepInEx.dll" />
    <Reference Include="UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.dll" />
  </ItemGroup>
</Project>
