<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>HighPredsMod</AssemblyName>
    <Product>HighPredsMod</Product>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>UnityEngine.XRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <RestoreAdditionalProjectSources>
      https://bepinex.dev
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

</Project>
