name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Move DLLs to root
        run: |
          cp -f *.dll ./ 2>/dev/null || true
          
      - name: Build
        run: dotnet build -c Release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HighPredsMod-DLL
          path: bin/Release/netstandard2.1/HighPredsMod.dll
